### ISSUE TITLE
Division by zero in linspace

### ISSUE THREAD

**Issue by vladh** [bpostlethwaite/arraytools#1]
linspace may divide by zero [here](https://github.com/bpostlethwaite/arraytools/blob/master/index.js#L15).

The line should instead read:

``` javascript
var inc = (end - start) / Math.max(num - 1, 1);
```

This causes [colormap issue #2](https://github.com/bpostlethwaite/colormap/issues/2).

**Comment by seeholza** [comment]
good find.
